#This is the name of the workflow which will be displayed in the actions tab
name: CICD

# Manually click(diliver) workflow user needed
on:
 workflow_dispatch:

jobs:
  code:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       run: echo "Copy code from Github"
  build:
     needs: code
     runs-on: ubuntu-latest
     steps:
       - name: Build your container
         run: echo "Docker Container build"
  test:
     needs: build
     runs-on: ubuntu-latest
     steps:
       - name: Test the container
         run: echo "Testing the container"
  deploy:
      needs: [build,test]
      runs-on: ubuntu-latest
      steps:
        - name: Deploy the app
          run: echo "Docker compose deployed the app"
  
  

   
