#name of workflow
name: Hello

#runs on an automatic trigger, whenever changes are pushed to the main branch (Deployment)
on:
  workflow_dispatch:
    inputs:
      environment:
        description: This is the environment where the workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
  #push:
   # branches:
    #  - main
#this is the name of the job
jobs:
  greet:
    #this is a GitHub runner, runs on a runner
    runs-on: ubuntu-latest
    steps:
      - name: say hello to user
        run: echo "Hello Dosto"
        
      - name: say hello to user
        run: echo "Hello $USER"

  details:
        runs-on: ubuntu-latest
        steps:
          - name: show what version of Python, Docker, etc
            run: docker --version && python --version
