#name of workflow
name: Run Python

#runs on automatic trigger
on:
  push:
    branches:
      - main
#this is the name of the job
jobs:
  run-Python:
    # This GitHub runner runs Son runner
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo"code fetched"
      - name: Show Python version
        run: python -- version
      
